### ISSUE TITLE
kube-ovn process priority and real-time kernel impact

### ISSUE THREAD

**Issue by krishnajs** [alauda/kube-ovn#223]
Hello, 
We are using kube-ovn and noticed that while deploying kube-ovn the priority of the kube-ovn process/threads are changed and it is lower than some of the kernel threads (lower is higher priority). Have you tested kube-ovn on Pre-empt RT kernel because we are seeing random system hangs especially with CPU isolation. What is the needed for changing the priority and where can we make OVN and OVS threads normal priority? Any insights much appreciated.

**Comment by oilbeater** [comment]
the ovs statr up scripts will change priority of ovs-db-server and ovs-vswitchd. The easiest way is to remove nice privilege of ovs pod here https://github.com/alauda/kube-ovn/blob/master/yamls/ovn.yaml#L163

Otherwise you need to change the start scripts to add desired priority https://github.com/alauda/kube-ovn/blob/master/dist/images/start-ovs.sh#L38 and https://github.com/alauda/kube-ovn/blob/master/dist/images/start-ovs.sh#L49 with option `--ovsdb-server-priority` and `--ovs-vswitchd-priority`

**Comment by amr-mokhtar** [comment]
Hi @oilbeater , We've been using kube-ovn with ovs on an RT kernel with isolcpu kernel cmdline options. The system hangs sooner or later with that configuration when using kube-ovn versions: v0.7.0, v0.8.0 and v0.10.2. We've tried to renice the ovn* & ovs* processes/threads on the worker node but that did not help much. The hanging problem is observed when the "kube-ovn-pinger" is deployed on the worked node.

I'd appreciate if you can provide any guidance of how we can further investigate & test kube-ovn with the above RT configurations. Also, regarding your comment above, we've tested the older version v.0.7.0 which does not have the `SYS_NICE` capability, and also we've manually reniced the ovn/ovs processes.

**Comment by oilbeater** [comment]
I am not familiar with RT kernel. The kube-ovn-pinger will do a periodically  ping check to other node/pod/dns/apiserver and expose it to prometheus. May be some operation will cause the cpu hang. Do you have any idea about what operation may cause the cpu hang?

The pinger will not affect any network function, so you can remove it from your deployment if possible. Otherwise we need to remove some codes to narrow down which part causes this problem.

**Comment by krishnajs** [comment]
The bug is resolved and pushed to both RHEL kernel-rt-3.10.0-1062.12.1.rt56.1042.el7 and Cent OS 3.10.0-1062.12.1.rt56.1042.el7.x86_64 . The bug relates to * kernel-rt:  hard lockup panic in during execution of CFS bandwidth period - timer (BZ#1788057)- https://linuxsecurity.com/advisories/red-hat/redhat-rhsa-2020-0375-01-important-kernel-rt-security-and-bug-fix-update-14-33-26
